name: "Payback Period"
definition: "The time required to recover the customer acquisition cost from the gross margin generated by that customer."
abbreviation: _
version: "1.0.0"
dependencies: []
sources: []
